backend:
  name: github
  repo: yoshivb/p4nth3rworld-wiki
  open_authoring: true

publish_mode: editorial_workflow

site_url: https://p4nth3rworld-wiki.netlify.app

media_folder: static/img
public_folder: /img

collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'content'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: 'Aside'
        name: 'asideInfo'
        widget: 'list'
        fields:
          - {label: 'Key', name: 'key', widget: 'text'}
          - {label: 'Value', name: 'value', widget: 'text'}
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'events'
    label: 'Events'
    folder: 'content/3.events'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: 'Aside'
        name: 'asideInfo'
        widget: 'list'
        fields:
          - {label: 'Key', name: 'key', widget: 'text'}
          - {label: 'Value', name: 'value', widget: 'text'}
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'locations'
    label: 'Locations'
    folder: 'content/2.locations'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: 'Aside'
        name: 'asideInfo'
        widget: 'list'
        fields:
          - {label: 'Key', name: 'key', widget: 'text'}
          - {label: 'Value', name: 'value', widget: 'text'}
      - { label: 'Body', name: 'body', widget: 'markdown' }