backend:
  name: github
  repo: yoshivb/p4nth3rworld-wiki
  open_authoring: true

publish_mode: editorial_workflow

site_url: https://p4nth3rworld-wiki.netlify.app

media_folder: static/img
public_folder: /img

collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'content/posts'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    nested:
      depth: 3 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - label: 'Aside'
        name: 'asideInfo'
        widget: 'list'
        fields:
          - {label: 'Key', name: 'key', widget: 'text'}
          - {label: 'Value', name: 'value', widget: 'text'}
      - { label: 'Body', name: 'body', widget: 'markdown' }